on:
  release:
    types: [published]

jobs:
  release:
    name: release ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: win
            artifact_glob: "./dist/win32/*.exe"
            runs-on: windows-latest
          - target: deb
            artifact_glob: "./dist/deb/*_amd64.deb"
            runs-on: ubuntu-latest

    runs-on: ${{ matrix.runs-on }}

    steps:
    - run: sudo apt update
      if: runner.os == 'Linux'
    - run: sudo apt install nsis p7zip-full p7zip-rar -y
      if: runner.os == 'Linux'
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.10.0'
    - name: Install dependencies
      run: npm ci
    - name: Build project
      run: npm run build
    - name: Install oclif globally
      run: npm install -g oclif
    - name: Setup MSys2 for Windows
      if: matrix.target == 'win'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: tar
    - name: Pack for target (Windows with MSys2)
      if: matrix.target == 'win'
      shell: msys2 {0}
      run: |
        export PATH="/mingw64/bin:$PATH"
        oclif pack win -r .
    - name: Pack for target (Linux)
      if: matrix.target == 'deb'
      run: oclif pack ${{ matrix.target }} -r .
    - name: Attach artifacts to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GH_TOKEN }}
        file: ${{ matrix.artifact_glob }}
        file_glob: true
        overwrite: true
        tag: ${{ github.ref }}
