on:
  release:
    types: [published]

jobs:
  release:
    name: release ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: win
            artifact_glob: './dist/win32/*'
            runs-on: windows-latest
          - target: deb
            artifact_glob: './dist/deb/*'
            runs-on: ubuntu-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - run: sudo apt update
        if: runner.os == 'Linux'
      - run: sudo apt install nsis p7zip-full p7zip-rar -y
        if: runner.os == 'Linux'
      - name: Setup MSYS2 with GNU tar (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: tar
          path-type: inherit
      - name: Prepend MSYS2 tar to PATH (Windows)
        if: runner.os == 'Windows'
        run: echo "C:\\msys64\\usr\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh
      - name: Install NSIS (Windows)
        if: runner.os == 'Windows'
        run: choco install nsis -y
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci || npm install
      - run: |
          if ($env:RUNNER_OS -eq "Windows") {
            npx oclif pack win -r . --targets win32-x64,win32-x86
          } else {
            npx oclif pack ${{ matrix.target }} -r .
          }
        shell: pwsh
      - name: Attach artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: ${{ matrix.artifact_glob }}
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
