on:
  release:
    types: [published]

jobs:
  release:
    name: release ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: win
            artifact_glob: "./dist/win32/*.exe"
            runs-on: windows-latest
          - target: deb
            artifact_glob: "./dist/deb/*_amd64.deb"
            runs-on: ubuntu-latest

    runs-on: ${{ matrix.runs-on }}

    steps:
    - run: sudo apt update
      if: runner.os == 'Linux'
    - run: sudo apt install nsis p7zip-full p7zip-rar -y
      if: runner.os == 'Linux'
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.10.0'
    - name: Install dependencies
      run: npm ci
    - name: Build project
      run: npm run build
    # Ensure GNU tar is available on Windows runners for oclif
    - name: Add GNU tar to PATH (Windows)
      if: matrix.target == 'win'
      run: echo "C:\msys64\usr\bin" >> %GITHUB_PATH%
      shell: cmd
    # Use npx so we don't rely on a global oclif in a different shell
    - name: Pack for target (Windows)
      if: matrix.target == 'win'
      run: npx oclif pack win -r .
    - name: Pack for target (Linux)
      if: matrix.target == 'deb'
      run: oclif pack ${{ matrix.target }} -r .
    - name: Attach artifacts to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GH_TOKEN }}
        file: ${{ matrix.artifact_glob }}
        file_glob: true
        overwrite: true
        tag: ${{ github.ref }}
