on:
  release:
    types: [published]

jobs:
  release:
    name: release deb
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update
      - run: sudo apt install nsis p7zip-full p7zip-rar -y
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci || npm install
      - name: Pack (deb)
        shell: bash
        run: npx oclif pack deb -r .
      - name: Pack (win)
        shell: bash
        run: npx oclif pack win -r .
      - name: Remove repo metadata
        shell: bash
        run: |
          find ./dist/deb -maxdepth 2 -type f \( -name 'Packages' -o -name 'Packages.*' -o -name 'Release' -o -name 'Release.*' \) -print -delete
      - name: Attach deb artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: './dist/deb/**/*.deb'
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
      - name: Attach win artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: './dist/win32/**/*.exe'
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
